"""create bp_readings table

Revision ID: 33fd9e1d2ac1
Revises: 4a37d63b0c93
Create Date: 2026-08-06 08:17:54.359594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fd9e1d2ac1'
down_revision: Union[str, Sequence[str], None] = '4a37d63b0c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_readings',
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index(op.f('ix_bp_readings_patient_id'), 'bp_readings', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bp_readings_patient_id'), table_name='bp_readings')
    op.drop_table('bp_readings')
    # ### end Alembic commands ###
