"""alter user table

Revision ID: 74956442016a
Revises: 8371df067ab9
Create Date: 2026-08-06 22:39:56.419426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74956442016a'
down_revision: Union[str, Sequence[str], None] = '8371df067ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('patient', 'clinician', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('patient', 'clinician', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###
