"""add notes column to bp_readings

Revision ID: 8371df067ab9
Revises: 33fd9e1d2ac1
Create Date: 2026-08-06 13:09:06.668194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8371df067ab9'
down_revision: Union[str, Sequence[str], None] = '33fd9e1d2ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bp_readings', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('bp_readings', 'heart_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bp_readings', 'heart_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bp_readings', 'notes')
    # ### end Alembic commands ###
